name: build_macos

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build_macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: test
        run: |
          gcc --version
          make test
      - name: build
        run: |
          make purge
          make all
